"""A copy of the part of the database that cannot be fetched again.

Automatic volume snapshots are off, deliberately: on one core, reading six
gigabytes off the volume every night took the site down for hours (see
DEPLOY.md). That decision is only defensible because of the shape of what is
stored. Of a 6.7 GB database, essentially all of it is news — 1.36 million
articles that the feeds will hand over again. What the feeds will never hand
back is the few megabytes describing *people*: accounts and their passwords,
the columns they built, the alerts they are waiting on, the organisations they
share with, the places they watch, and the outlets they added by hand.

So this exports that, and only that. It is small enough to keep anywhere, and
losing it is the only part of losing the volume that cannot be undone.

Two things this is careful about.

*References survive.* Feeds address their owner as the string "acct:<id>",
pantheon membership is by numeric user id, and a watched place points at the
feed and the source created for it. Restore into a fresh database and every one
of those ids would be reassigned, so the ids are preserved rather than
regenerated. Sources are the exception and have to be: the catalog re-seeds
itself on first boot and would take the low ids for itself, so sources are
matched on `rss_url` — which is unique — and the references to them rewritten.

*It refuses rather than half-works.* Restoring into a database that already has
accounts would either collide on ids or silently graft one person's feeds onto
another's account. There is no merge here; there is a restore into an empty
account set, and a clear refusal otherwise.

Deliberately not included: read markers (ViewedArticle/ViewedEvent — hundreds of
thousands of rows recording which stories have been seen, regenerated by
reading), alert history (it points at articles that will not exist), device
records (a browser re-registers on its next request), and the catalog's own
sources (re-seeded, and re-discovered).

CONTAINS SECRETS. Password hashes, email addresses, alert webhook URLs. Treat a
copy of this as you would the database itself. In particular it must never be
printed by the "Run a Fly command" workflow: this repository is public, and so
are its Actions logs.
"""
from __future__ import annotations

import hashlib
import json
import logging
import os
from datetime import datetime

from sqlalchemy import select
from sqlalchemy.orm import Session

from . import mailer
from .models import (Alert, FavoriteLocation, Feed, Pantheon, PantheonInvite,
                     PantheonMember, Source, User, utcnow)

log = logging.getLogger("accounts_backup")

# Bumped when the shape changes in a way an older restore could not read.
# Checked on restore, because a wrong guess about the shape of a backup is
# discovered at the worst possible moment.
FORMAT = 1

# The tables a restore writes into. Named once, so the emptiness check and the
# wipe cannot drift apart from what is actually restored.
_RESTORED = (User, Pantheon, PantheonMember, PantheonInvite, Feed, Alert,
             FavoriteLocation)


def _dt(value: datetime | None) -> str | None:
    return value.isoformat() if value is not None else None


def _parse_dt(value: str | None) -> datetime | None:
    return datetime.fromisoformat(value) if value else None


# ---------- export ----------

def _user(u: User) -> dict:
    return {
        "id": u.id,
        "username": u.username,
        "email": u.email,
        "email_verified": u.email_verified,
        "password_hash": u.password_hash,
        "created_at": _dt(u.created_at),
        "last_seen_at": _dt(u.last_seen_at),
        # Kept so a restored account is not told about a year of updates it
        # has already read.
        "changelog_seen": u.changelog_seen,
        "settings": u.settings,
        "is_admin": u.is_admin,
        "disabled": u.disabled,
        # Restored as-is rather than reset to zero: every issued token carries
        # the number it was minted under, and lowering it would make old
        # tokens valid again.
        "token_version": u.token_version,
        "device_limit": u.device_limit,
    }


def _source(s: Source) -> dict:
    """Enough to recreate the source, and nothing about how polling is going.

    Deliberately without etag, last_fetched_at, failure counts or idle_polls:
    those describe a conversation with a server that will be started again from
    scratch, and restoring them would have the poller act on what it believed
    weeks ago.
    """
    return {
        "rss_url": s.rss_url,
        "name": s.name,
        "homepage": s.homepage,
        "country": s.country,
        "region": s.region,
        "language": s.language,
        "scope": s.scope,
        "categories": s.categories,
        "platform": s.platform,
        "paywall": s.paywall,
        "tier": s.tier,
        "enabled": s.enabled,
        "added_by": s.added_by,
    }


def _feed(f: Feed) -> dict:
    return {
        "id": f.id, "user_id": f.user_id, "pantheon_id": f.pantheon_id,
        "shared_by": f.shared_by, "name": f.name, "criteria": f.criteria,
        "sort": f.sort, "group_events": f.group_events,
        "position": f.position, "width": f.width,
        "created_at": _dt(f.created_at),
    }


def _alert(a: Alert) -> dict:
    return {
        "id": a.id, "user_id": a.user_id, "pantheon_id": a.pantheon_id,
        "shared_by": a.shared_by, "name": a.name, "criteria": a.criteria,
        "active": a.active, "notify_email": a.notify_email,
        "webhook_url": a.webhook_url, "created_at": _dt(a.created_at),
        "last_triggered_at": _dt(a.last_triggered_at),
    }


def _location(loc: FavoriteLocation, source_url: str | None) -> dict:
    """`source_url` replaces source_id: ids are reassigned by the re-seed, the
    feed URL is not."""
    return {
        "id": loc.id, "user_id": loc.user_id, "pantheon_id": loc.pantheon_id,
        "shared_by": loc.shared_by, "name": loc.name,
        "place_name": loc.place_name, "country": loc.country,
        "lat": loc.lat, "lon": loc.lon, "radius_km": loc.radius_km,
        "color": loc.color, "feed_id": loc.feed_id,
        "source_url": source_url,
        "created_at": _dt(loc.created_at),
    }


def build(db: Session) -> dict:
    """The whole irreplaceable set, as one document."""
    users = db.scalars(select(User).order_by(User.id)).all()
    pantheons = db.scalars(select(Pantheon).order_by(Pantheon.id)).all()
    members = db.scalars(select(PantheonMember).order_by(PantheonMember.id)).all()
    invites = db.scalars(select(PantheonInvite).order_by(PantheonInvite.id)).all()
    feeds = db.scalars(select(Feed).order_by(Feed.id)).all()
    alerts = db.scalars(select(Alert).order_by(Alert.id)).all()
    locations = db.scalars(
        select(FavoriteLocation).order_by(FavoriteLocation.id)).all()

    # Sources worth keeping are the ones nothing else would recreate: the ones
    # a person added, and the per-place search sources a watched location owns.
    # The seeded catalog is left out on purpose — it is in the repository.
    wanted_ids = {loc.source_id for loc in locations if loc.source_id}
    by_id = {s.id: s for s in db.scalars(
        select(Source).where(Source.added_by == "user")).all()}
    for sid in wanted_ids:
        if sid not in by_id:
            s = db.get(Source, sid)
            if s is not None:
                by_id[s.id] = s
    # A feed's criteria can pin specific source_ids too. Those are usually
    # catalog sources, which the re-seed provides, so they are not dragged in
    # here — but a user-added one among them is already covered above.

    doc = {
        "format": FORMAT,
        "taken_at": utcnow().isoformat() + "Z",
        "users": [_user(u) for u in users],
        "pantheons": [{
            "id": p.id, "name": p.name, "description": p.description,
            "visibility": p.visibility, "owner_id": p.owner_id,
            "settings": p.settings, "created_at": _dt(p.created_at),
        } for p in pantheons],
        "pantheon_members": [{
            "id": m.id, "pantheon_id": m.pantheon_id, "user_id": m.user_id,
            "role": m.role, "joined_at": _dt(m.joined_at),
        } for m in members],
        "pantheon_invites": [{
            "id": i.id, "pantheon_id": i.pantheon_id, "user_id": i.user_id,
            "invited_by": i.invited_by, "created_at": _dt(i.created_at),
        } for i in invites],
        "sources": [_source(s) for s in by_id.values()],
        "feeds": [_feed(f) for f in feeds],
        "alerts": [_alert(a) for a in alerts],
        "locations": [
            _location(loc, by_id[loc.source_id].rss_url
                      if loc.source_id in by_id else None)
            for loc in locations],
    }
    doc["counts"] = {k: len(v) for k, v in doc.items() if isinstance(v, list)}
    return doc


def to_json(doc: dict) -> bytes:
    return json.dumps(doc, ensure_ascii=False, indent=1).encode("utf-8")


def filename(doc: dict) -> str:
    return f"delphi-accounts-{doc['taken_at'][:10]}.json"


def digest(doc: dict) -> str:
    """A fingerprint of the *contents*, ignoring when it was taken.

    So a system where nothing changed does not mail an identical file every day.
    `taken_at` and `counts` are excluded deliberately: the first always differs
    and the second is derived, so including either would make every backup look
    new and turn a safety net into a daily notification nobody reads.
    """
    payload = {k: v for k, v in doc.items()
               if k not in ("taken_at", "counts")}
    return hashlib.sha256(
        json.dumps(payload, ensure_ascii=False, sort_keys=True).encode("utf-8")
    ).hexdigest()[:16]


# ---------- sending it somewhere that is not this machine ----------

# How often to mail a copy. Zero switches it off. Daily by default: the file is
# kilobytes, and the thing it protects against is losing the volume, which does
# not announce itself in advance.
EVERY_SECONDS = float(os.environ.get("NEWS_ACCOUNT_BACKUP_EVERY_S",
                                    str(24 * 3600)))
# Where to send it. Empty means "every operator account with an email", which is
# the right default: the people who could restore it.
TO = os.environ.get("NEWS_ACCOUNT_BACKUP_TO", "").strip()


def recipients(db: Session) -> list[str]:
    """Who gets the copy.

    An explicit address wins. Otherwise every operator account with an email —
    not every account, because this file is every account's password hash and
    handing it to all of them would be a breach dressed as a backup.
    """
    if TO:
        return [addr.strip() for addr in TO.split(",") if addr.strip()]
    return [u.email for u in db.scalars(
        select(User).where(User.is_admin.is_(True), User.email != "")).all()]


# What the scheduled copy has been doing, surfaced through /api/ingest/status
# so a backup that silently stopped is visible without reading a log — the
# failure mode of every backup that has ever mattered.
status: dict = {
    "last_sent_at": None,
    "last_sent_to": 0,
    "last_digest": None,
    "last_skipped_reason": None,
    "sent_total": 0,
}


def send_scheduled(db: Session) -> dict:
    """Build a backup and mail it, unless there is nothing new to say.

    Returns what it did, and records the same in `status`. Never raises: this
    runs inside the poll loop, and a mail relay having a bad day must not stop
    the news being collected.
    """
    try:
        doc = build(db)
        fresh = digest(doc)
        if fresh == status["last_digest"]:
            status["last_skipped_reason"] = "nothing changed since the last copy"
            return {"sent": 0, "reason": status["last_skipped_reason"]}

        to = recipients(db)
        if not to:
            status["last_skipped_reason"] = (
                "no operator account has an email address to send it to")
            log.warning("account backup not sent: %s", status["last_skipped_reason"])
            return {"sent": 0, "reason": status["last_skipped_reason"]}

        body = (
            "Attached is a copy of the D.E.L.P.H.I. account data for "
            f"{doc['taken_at'][:10]}: {doc['counts']['users']} account(s), "
            f"{doc['counts']['feeds']} column(s), {doc['counts']['alerts']} "
            f"alert(s), {doc['counts']['locations']} watched place(s).\n\n"
            "This is the part of the database the feeds cannot provide again. "
            "The news itself is not included, which is why this is kilobytes "
            "rather than gigabytes.\n\n"
            "It contains password hashes and alert webhook addresses. Keep it "
            "as you would keep the database.\n\n"
            "To restore onto a rebuilt machine:\n"
            "  python -m backend.app.accounts_backup restore <file> --dry-run\n"
            "  python -m backend.app.accounts_backup restore <file>\n")
        payload = to_json(doc)
        sent = 0
        for address in to:
            if mailer.send_attachment(
                    address,
                    f"D.E.L.P.H.I. account backup — {doc['taken_at'][:10]}",
                    body, filename=filename(doc), data=payload):
                sent += 1

        if sent:
            # Only remember the digest once a copy actually left, or a failed
            # relay would be recorded as "nothing changed" and never retried.
            status["last_digest"] = fresh
            status["last_sent_at"] = doc["taken_at"]
            status["last_sent_to"] = sent
            status["last_skipped_reason"] = None
            status["sent_total"] += 1
            log.info("account backup mailed to %d recipient(s), %d bytes",
                     sent, len(payload))
        else:
            status["last_skipped_reason"] = "mail could not be delivered"
        return {"sent": sent, "bytes": len(payload), "counts": doc["counts"]}
    except Exception as exc:                     # never break the poll loop
        status["last_skipped_reason"] = f"{type(exc).__name__}: {exc}"[:200]
        log.exception("account backup failed")
        return {"sent": 0, "reason": status["last_skipped_reason"]}


# ---------- restore ----------

class RestoreRefused(Exception):
    """The backup will not be applied, and nothing has been written."""


def occupied(db: Session) -> list[str]:
    """Which restore targets already hold rows. Empty means safe to restore."""
    busy = []
    for model in _RESTORED:
        if db.scalar(select(model.id).limit(1)) is not None:
            busy.append(model.__tablename__)
    return busy


def _wipe(db: Session) -> None:
    """Clear the account tables, children before parents.

    Only ever reached through an explicit choice, and never over HTTP: the
    caller has said they intend to replace the accounts on this machine with
    the ones in a file.
    """
    for model in reversed(_RESTORED):
        db.query(model).delete(synchronize_session=False)
    db.flush()
    # The rows are gone but the session still has the objects, so re-inserting
    # the same primary keys would be seen as conflicting with instances it
    # believes are already persistent. Forget them: what is authoritative now
    # is the file being restored.
    db.expunge_all()


def restore(db: Session, doc: dict, *, dry_run: bool = False,
            replace: bool = False) -> dict:
    """Write a backup back into an empty account set.

    Refuses when accounts already exist unless `replace` is set, which clears
    them first. There is no merge: two databases that both have a user id 3
    cannot be reconciled without deciding whose feeds those are, and a backup
    tool guessing that is worse than one that declines.
    """
    got = doc.get("format")
    if got != FORMAT:
        raise RestoreRefused(
            f"backup is format {got!r}, this build restores format {FORMAT}")

    busy = occupied(db)
    if busy and not replace:
        raise RestoreRefused(
            "this database already has accounts in " + ", ".join(busy) +
            " — restoring would collide with them. Use replace to clear them "
            "first, or restore onto a fresh volume.")

    plan = {"users": len(doc.get("users", [])),
            "pantheons": len(doc.get("pantheons", [])),
            "pantheon_members": len(doc.get("pantheon_members", [])),
            "pantheon_invites": len(doc.get("pantheon_invites", [])),
            "feeds": len(doc.get("feeds", [])),
            "alerts": len(doc.get("alerts", [])),
            "locations": len(doc.get("locations", [])),
            "sources_in_backup": len(doc.get("sources", [])),
            "replaced": busy if replace else [],
            "dry_run": dry_run}
    if dry_run:
        return plan

    if busy:
        _wipe(db)

    for row in doc.get("users", []):
        db.add(User(
            id=row["id"], username=row["username"], email=row.get("email", ""),
            email_verified=row.get("email_verified", False),
            password_hash=row["password_hash"],
            created_at=_parse_dt(row.get("created_at")) or utcnow(),
            last_seen_at=_parse_dt(row.get("last_seen_at")),
            changelog_seen=row.get("changelog_seen"),
            settings=row.get("settings"),
            is_admin=row.get("is_admin", False),
            disabled=row.get("disabled", False),
            token_version=row.get("token_version", 0),
            device_limit=row.get("device_limit")))
    db.flush()

    for row in doc.get("pantheons", []):
        db.add(Pantheon(
            id=row["id"], name=row["name"],
            description=row.get("description", ""),
            visibility=row.get("visibility", "private"),
            owner_id=row["owner_id"], settings=row.get("settings") or {},
            created_at=_parse_dt(row.get("created_at")) or utcnow()))
    db.flush()

    for row in doc.get("pantheon_members", []):
        db.add(PantheonMember(
            id=row["id"], pantheon_id=row["pantheon_id"],
            user_id=row["user_id"], role=row.get("role", "member"),
            joined_at=_parse_dt(row.get("joined_at")) or utcnow()))
    for row in doc.get("pantheon_invites", []):
        db.add(PantheonInvite(
            id=row["id"], pantheon_id=row["pantheon_id"],
            user_id=row["user_id"], invited_by=row["invited_by"],
            created_at=_parse_dt(row.get("created_at")) or utcnow()))
    db.flush()

    # Sources by URL, not by id: whatever the re-seed already created keeps its
    # id, and only what is genuinely missing is added.
    source_ids: dict[str, int] = {}
    added_sources = 0
    for row in doc.get("sources", []):
        url = row["rss_url"]
        existing = db.scalar(select(Source).where(Source.rss_url == url))
        if existing is None:
            existing = Source(**row)
            db.add(existing)
            db.flush()
            added_sources += 1
        source_ids[url] = existing.id
    plan["sources_added"] = added_sources

    for row in doc.get("feeds", []):
        db.add(Feed(
            id=row["id"], user_id=row["user_id"],
            pantheon_id=row.get("pantheon_id"),
            shared_by=row.get("shared_by", ""), name=row["name"],
            criteria=row.get("criteria") or {},
            sort=row.get("sort", "newest"),
            group_events=row.get("group_events", False),
            position=row.get("position", 0), width=row.get("width", 1),
            created_at=_parse_dt(row.get("created_at")) or utcnow()))
    for row in doc.get("alerts", []):
        db.add(Alert(
            id=row["id"], user_id=row["user_id"],
            pantheon_id=row.get("pantheon_id"),
            shared_by=row.get("shared_by", ""), name=row["name"],
            criteria=row.get("criteria") or {},
            active=row.get("active", True),
            notify_email=row.get("notify_email", False),
            webhook_url=row.get("webhook_url", ""),
            created_at=_parse_dt(row.get("created_at")) or utcnow(),
            last_triggered_at=_parse_dt(row.get("last_triggered_at"))))
    db.flush()

    for row in doc.get("locations", []):
        url = row.get("source_url")
        db.add(FavoriteLocation(
            id=row["id"], user_id=row["user_id"],
            pantheon_id=row.get("pantheon_id"),
            shared_by=row.get("shared_by", ""), name=row["name"],
            place_name=row.get("place_name", ""),
            country=row.get("country", ""),
            lat=row["lat"], lon=row["lon"],
            radius_km=row.get("radius_km", 25.0),
            color=row.get("color", "gold"),
            feed_id=row.get("feed_id"),
            # None when the source is gone: the place keeps working off the
            # gazetteer, it simply stops having a search feed of its own.
            source_id=source_ids.get(url) if url else None,
            created_at=_parse_dt(row.get("created_at")) or utcnow()))

    db.commit()
    log.info("restored accounts backup taken %s: %s",
             doc.get("taken_at"), plan)
    return plan


# ---------- command line ----------

def _main(argv: list[str]) -> int:
    """Restoring needs no account to sign in with.

    The reason this exists as a command and not only as an endpoint: the moment
    a backup is needed is the moment the database is empty, and an
    operator-only endpoint on an empty database has nobody to authorise it.
    Run inside the machine, against the volume, before anyone signs in:

        python -m backend.app.accounts_backup export /data/accounts.json
        python -m backend.app.accounts_backup restore /data/accounts.json
    """
    import argparse

    from .database import SessionLocal

    parser = argparse.ArgumentParser(prog="accounts_backup",
                                     description=__doc__.split("\n")[0])
    parser.add_argument("action", choices=("export", "restore"))
    parser.add_argument("path")
    parser.add_argument("--replace", action="store_true",
                        help="clear existing accounts before restoring")
    parser.add_argument("--dry-run", action="store_true",
                        help="report what a restore would do, write nothing")
    args = parser.parse_args(argv)

    db = SessionLocal()
    try:
        if args.action == "export":
            doc = build(db)
            with open(args.path, "wb") as fh:
                fh.write(to_json(doc))
            print(f"wrote {args.path}: {doc['counts']}")
            return 0

        with open(args.path, "rb") as fh:
            doc = json.loads(fh.read().decode("utf-8"))
        try:
            print(restore(db, doc, dry_run=args.dry_run, replace=args.replace))
        except RestoreRefused as exc:
            print(f"refused: {exc}")
            return 1
        return 0
    finally:
        db.close()


if __name__ == "__main__":  # pragma: no cover - exercised as a command
    import sys
    raise SystemExit(_main(sys.argv[1:]))
